# i3status configuration file.
# see "man i3status" for documentation.

# It is important that this file is edited as UTF-8.
# The following line should contain a sharp s:
# ß
# If the above line is not correctly displayed, fix your editor first!
general {
    colors = true
    interval = 5
}

order += "wireless wlp1s0"
order += "battery 0"
order += "cpu_temperature 0"
order += "disk /"
order += "memory"
order += "tztime local"

# Internet connection status
wireless wlp1s0 {
  format_up = "Leaked IP: (%quality at %essid, %bitrate) %ip"
  format_down = "Help me"
}
# Battery status
battery 0 {
  format = "%status %percentage R: %remaining"
  format_down = "Gay"
  status_chr = "⚡ CHR"
  status_bat = "Fairy dust"
  status_unk = "huh ?"
  status_full = "Nale o izet"
  status_idle = "..."
  path = "/sys/class/power_supply/BAT%d/uevent"
  low_threshold = 20
}
# Timezone
tztime local {
  format = "Happy new Year %Y-%m-%d %H:%M:%S"
}

# Load status
load {
  format = "L: %5min"
}

# Memory stuff IMPORTANT
memory {
  format = "%used"
  threshold_degraded = "20%"
  format_degraded = "BOOOM: %free"
}

# Available disk space
disk "/" {
  format = "%avail"
}


